name: Build Test

on:
  pull_request:
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on
  workflow_dispatch:

jobs:
  build-test:
    name: Build Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .  # Docusaurus is now at repo root
        
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      
      - name: Detect package manager
        id: detect-package-manager
        run: |
          # 检查根目录 package manager：
          if [ -f "pnpm-lock.yaml" ]; then
              echo "manager=pnpm" >> $GITHUB_OUTPUT
              echo "command=install --prefer-offline" >> $GITHUB_OUTPUT
              echo "runner=pnpm" >> $GITHUB_OUTPUT
              exit 0
          elif [ -f "yarn.lock" ]; then
            echo "manager=yarn" >> $GITHUB_OUTPUT
            echo "command=install --prefer-offline --no-audit" >> $GITHUB_OUTPUT
            echo "runner=yarn" >> $GITHUB_OUTPUT
            exit 0
          elif [ -f "package.json" ]; then
            echo "manager=npm" >> $GITHUB_OUTPUT
            echo "command=ci --prefer-offline --no-audit" >> $GITHUB_OUTPUT
            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "Unable to determine package manager"
            exit 1
          fi

      - name: Setup pnpm
        if: steps.detect-package-manager.outputs.manager == 'pnpm'
        uses: pnpm/action-setup@v6
        with:
          version: latest

      - uses: actions/setup-node@v7
        with:
          node-version: latest
          cache: ${{ steps.detect-package-manager.outputs.manager }}
          # 缓存路径指向根目录 pnpm-lock.yaml
          cache-dependency-path: pnpm-lock.yaml

      # NOTE: In CI environments (GitHub Actions sets CI=true automatically),
      # pnpm defaults to `--frozen-lockfile`
      - name: Install dependencies
        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}

      - name: Test build website
        run: ${{ steps.detect-package-manager.outputs.manager }} run build